In [11]:
import numpy as np

Задание 1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [59]:
n = np.arange(0, 9)
np.flip(n)

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [66]:
matrix = np.diag(np.arange(0, 10, 1), k=0)
matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [67]:
count = 0
for x in matrix:
    count += sum(x)
print(count)

45


Задание 3. Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [12]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Задание 4.

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [4]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [10]:
import matplotlib.pyplot as plt

def cosine( a, b ):
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )   
    return np.dot( a, b ) / ( aLength * bLength )

results = []
for user in users_stats:
    np.arccos(cosine(user, next_user_stats))*360/2/np.pi
    results.append(np.arccos(cosine(user, next_user_stats))*360/2/np.pi)

similar_user_id = (results.index(min(results))) + 1

print(f'ID {similar_user_id}, {min(results)}')

ID 8, 18.434948822922017
